name: CI-DevSecOps

on:
  push:
    branches: [ "main" ]
    tags: ['v*.*.*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Secret Scanning(Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests (Pytest)
        run: |
          pytest test_app.py

      - name: Codebase Security Scan (Trivy FS)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1' # 发现高危漏洞则报错
          severity: 'CRITICAL,HIGH'

  build-and-push:
    needs: test-and-scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lowercase the repo name
        run: echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          # 使用转为小写后的变量
          images: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}

      - name: Build Docker image (Load for Scan)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          # 使用转为小写后的变量
          tags: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:security-check
          cache-from: type=gha

      - name: Image Vulnerability Scan (Trivy Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:security-check
          format: 'table'
          exit-code: '0'  #先暂时允许漏洞的存在
          severity: 'CRITICAL,HIGH'

      - name: Build and push Docker image (Final)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max